/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BuildExpenseLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addExpense"
      | "getEncryptedMonthlyTotal"
      | "getExpenseRecord"
      | "getExpenseRecordCount"
      | "hasInitialized"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExpenseAdded" | "MonthlyTotalUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExpense",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedMonthlyTotal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpenseRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpenseRecordCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasInitialized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addExpense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedMonthlyTotal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpenseRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpenseRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace ExpenseAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    timestamp: BigNumberish,
    category: string
  ];
  export type OutputTuple = [user: string, timestamp: bigint, category: string];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonthlyTotalUpdatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BuildExpenseLedger extends BaseContract {
  connect(runner?: ContractRunner | null): BuildExpenseLedger;
  waitForDeployment(): Promise<this>;

  interface: BuildExpenseLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addExpense: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike, category: string],
    [void],
    "nonpayable"
  >;

  getEncryptedMonthlyTotal: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getExpenseRecord: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [[bigint, string] & { timestamp: bigint; category: string }],
    "view"
  >;

  getExpenseRecordCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  hasInitialized: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addExpense"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedMonthlyTotal"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getExpenseRecord"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [[bigint, string] & { timestamp: bigint; category: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExpenseRecordCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasInitialized"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ExpenseAdded"
  ): TypedContractEvent<
    ExpenseAddedEvent.InputTuple,
    ExpenseAddedEvent.OutputTuple,
    ExpenseAddedEvent.OutputObject
  >;
  getEvent(
    key: "MonthlyTotalUpdated"
  ): TypedContractEvent<
    MonthlyTotalUpdatedEvent.InputTuple,
    MonthlyTotalUpdatedEvent.OutputTuple,
    MonthlyTotalUpdatedEvent.OutputObject
  >;

  filters: {
    "ExpenseAdded(address,uint256,string)": TypedContractEvent<
      ExpenseAddedEvent.InputTuple,
      ExpenseAddedEvent.OutputTuple,
      ExpenseAddedEvent.OutputObject
    >;
    ExpenseAdded: TypedContractEvent<
      ExpenseAddedEvent.InputTuple,
      ExpenseAddedEvent.OutputTuple,
      ExpenseAddedEvent.OutputObject
    >;

    "MonthlyTotalUpdated(address,uint256)": TypedContractEvent<
      MonthlyTotalUpdatedEvent.InputTuple,
      MonthlyTotalUpdatedEvent.OutputTuple,
      MonthlyTotalUpdatedEvent.OutputObject
    >;
    MonthlyTotalUpdated: TypedContractEvent<
      MonthlyTotalUpdatedEvent.InputTuple,
      MonthlyTotalUpdatedEvent.OutputTuple,
      MonthlyTotalUpdatedEvent.OutputObject
    >;
  };
}
